# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServflowPro < Formula
  desc "ServFlow Pro - API management and testing tool"
  homepage "https://github.com/Servflow/servflow-pro"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.0/servflow-pro_Darwin_x86_64.tar.gz"
      sha256 "a71830bb9cdcbf7b01e6a71517b5a7085885686d066df0a130007b78488f2a51"

      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.0/servflow-pro_Darwin_arm64.tar.gz"
      sha256 "97339c2f38a759eff0851030918182d27923a70c5cb486b420480b703d5e9806"

      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.0/servflow-pro_Linux_x86_64.tar.gz"
      sha256 "00ddfe9d64dc59fd98767f71c277fc3e3ba3ea48c2f73600efb5521937dd94c4"
      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.0/servflow-pro_Linux_arm64.tar.gz"
      sha256 "0dd050cd87bca79a387f21887c182165cd640277aefee7eb077fef50a0a35ea1"
      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
  end
end
