# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServflowPro < Formula
  desc "ServFlow Pro - API management and testing tool"
  homepage "https://github.com/Servflow/servflow-pro"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.1.17/servflow-pro_Darwin_x86_64.tar.gz"
      sha256 "7536de7ed59a634a1f62c60a4f443ef40ebfd7fc481715bf70a7dde53e3e0767"

      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.1.17/servflow-pro_Darwin_arm64.tar.gz"
      sha256 "a62470e0609802c87ad752f582a941588d20ec6155d17c1a4dc123827791eab5"

      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.1.17/servflow-pro_Linux_x86_64.tar.gz"
      sha256 "0de0edf3dc9d3ac29852d22564d98efccff9a851feb9a619d0b48ab8948e8aa5"
      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.1.17/servflow-pro_Linux_arm64.tar.gz"
      sha256 "64279ec29ed21f0a52db4acfa45c2b62ce2aadd3674494fd1607dc1028b2d398"
      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
  end
end
