# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servflow < Formula
  desc "ServFlow - API management and testing tool"
  homepage "https://github.com/Servflow/servflow-pro"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.4/servflow_Darwin_x86_64.tar.gz"
      sha256 "82985e6d9987a8ddb704b50cd8ca59a877b895a2008a65a3d6fc477351a790d7"

      define_method(:install) do
        bin.install "servflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.4/servflow_Darwin_arm64.tar.gz"
      sha256 "9952d0e75d9c760198cbe3aaaf50b3c2a3f712c4ceb396ccbcc5faa87b707a1b"

      define_method(:install) do
        bin.install "servflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.4/servflow_Linux_x86_64.tar.gz"
      sha256 "a7fd8c573f5e7d21283a1dc732e7b3d9356807f1be74c80a85e9689b463a3489"
      define_method(:install) do
        bin.install "servflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.4/servflow_Linux_arm64.tar.gz"
      sha256 "419c58aeae83b9f41e911b54f1754e839428818865d64e7ec37524981ea6d0c4"
      define_method(:install) do
        bin.install "servflow"
      end
    end
  end
end
