# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ServflowPro < Formula
  desc "ServFlow Pro - API management and testing tool"
  homepage "https://github.com/Servflow/servflow-pro"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.1/servflow-pro_Darwin_x86_64.tar.gz"
      sha256 "7dc370d58ee15db2f0d71a068d40a39fdf39bcd709ba97d7a4cf573403595c0b"

      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.1/servflow-pro_Darwin_arm64.tar.gz"
      sha256 "9640c10efadeee764f93cbb85884136c9e784fcd8a36f7531327fe30c2f618cc"

      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.1/servflow-pro_Linux_x86_64.tar.gz"
      sha256 "26a49c4ddc162135a7c1a8998a6df79d39634d022410fe778b6ab84bcd5f51dc"
      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.1/servflow-pro_Linux_arm64.tar.gz"
      sha256 "95ff2de93a87a5efca67411af294f3cec7dffaf84bfe90fe4065262352cd76e4"
      define_method(:install) do
        bin.install "servflow-pro"
      end
    end
  end
end
