# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servflow < Formula
  desc "ServFlow - API management and testing tool"
  homepage "https://github.com/Servflow/servflow-pro"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.3/servflow_Darwin_x86_64.tar.gz"
      sha256 "8c6b9c635cbecb5b521305880f6a488ab10de5e04e2a97ef864318fec40353ec"

      define_method(:install) do
        bin.install "servflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.3/servflow_Darwin_arm64.tar.gz"
      sha256 "00bc60ad91fec247f12f9cf83374a182cc92a43cea7578697d3b60f13cdab81f"

      define_method(:install) do
        bin.install "servflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.3/servflow_Linux_x86_64.tar.gz"
      sha256 "4e7409351e71f6c123bc2b9c5e27dd08f540ee10e63af596bca817e2dcc77493"
      define_method(:install) do
        bin.install "servflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Servflow/servflow-pro/releases/download/v0.2.3/servflow_Linux_arm64.tar.gz"
      sha256 "77b74b670db1239dcc54902e21a2101d08c1d8184ba5a77f49cdc08067b9d399"
      define_method(:install) do
        bin.install "servflow"
      end
    end
  end
end
